services:
  backend:
    build: ./backend
    container_name: MiniStore_Backend
    restart: always
    environment:
      PORT: 3000
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_APIKEY: ${SUPABASE_APIKEY}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - ministore-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: MiniStore_Frontend
    restart: always
    environment:
      VITE_API_URL: http://localhost:3000/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - ministore-network

  mobile:
    build: ./mobile
    container_name: MiniStore_Mobile
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./mobile:/app
      - /app/node_modules
      - /app/.expo
    stdin_open: true
    tty: true

networks:
  ministore-network:
    driver: bridge
