-- ============================================================
-- BASE DE DATOS: Ariel's Jewelry
-- Generado desde el frontend de la aplicación académica
-- ============================================================

-- ============================================================
-- TABLA: usuarios
-- Fuente: LoginPage.jsx — registro e inicio de sesión
-- Campos: username (mín. 3 chars), password (mín. 8 chars,
--         mayúsc, minúsc, número, carácter especial)
-- ============================================================
CREATE TABLE usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- TABLA: productos
-- Fuente: ProductsPage.jsx — CRUD completo (crear, editar, eliminar)
-- Campos del formulario: name, price, image_url, featured
-- ============================================================
CREATE TABLE productos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)   NOT NULL,
    price           DECIMAL(12, 2) NOT NULL CHECK (price > 0),
    image_url       VARCHAR(500),
    featured        BOOLEAN        DEFAULT FALSE,
    activo          BOOLEAN        DEFAULT TRUE,
    created_at      TIMESTAMPTZ    DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- TABLA: clientes
-- Fuente: CustomersPage.jsx — crear y eliminar
-- Campos del formulario: name, phone, email
-- ============================================================
CREATE TABLE clientes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150)  NOT NULL,
    phone           VARCHAR(20)   NOT NULL,
    email           VARCHAR(100)  NOT NULL UNIQUE,
    created_at      TIMESTAMPTZ   DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- TABLA: pedidos
-- Fuente: OrdersPage.jsx — crear y eliminar
-- Campos del formulario: producto (FK), quantity, cliente (FK opcional),
--                        notes (texto libre opcional)
-- Total se calcula en backend: price * quantity
-- ============================================================
CREATE TABLE pedidos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto     BIGINT         NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
    id_cliente      BIGINT         REFERENCES clientes(id) ON DELETE SET NULL,
    product_name    VARCHAR(255)   NOT NULL,
    quantity        INT            NOT NULL CHECK (quantity > 0),
    total           DECIMAL(12, 2) NOT NULL CHECK (total > 0),
    notes           TEXT,
    created_at      TIMESTAMPTZ    DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- ÍNDICES
-- ============================================================
CREATE INDEX idx_productos_activo   ON productos (activo);
CREATE INDEX idx_clientes_email     ON clientes  (email);
CREATE INDEX idx_pedidos_producto   ON pedidos   (id_producto);
CREATE INDEX idx_pedidos_cliente    ON pedidos   (id_cliente);
CREATE INDEX idx_pedidos_created_at ON pedidos   (created_at);

-- ============================================================
-- DATOS INICIALES
-- ============================================================

-- Productos de ejemplo
INSERT INTO productos (name, price, image_url, featured) VALUES
    ('Collar de perlas',  25000, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400', true),
    ('Pulsera de plata',  15000, 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400', false),
    ('Aretes de oro',     35000, 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=400', true),
    ('Anillo de plata',   18000, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400', false);

-- Clientes de ejemplo
INSERT INTO clientes (name, phone, email) VALUES
    ('María González', '300-123-4567', 'maria@email.com'),
    ('Carlos López',   '300-567-8901', 'carlos@email.com'),
    ('Ana Martínez',   '300-901-2345', 'ana@email.com');
