-- ============================================
-- BASE DE DATOS: Sistema de Ventas -
-- ============================================

-- Tipos ENUM personalizados
DROP TYPE IF EXISTS producto_tamano CASCADE;
CREATE TYPE producto_tamano AS ENUM ('pequeño', 'mediano', 'grande', 'unico');

DROP TYPE IF EXISTS pedido_estado CASCADE;
CREATE TYPE pedido_estado AS ENUM ('pendiente', 'en_proceso', 'completado', 'entregado', 'cancelado');

-- ============================================
-- TABLAS PRINCIPALES
-- ============================================

-- Tabla: CATEGORIAS
CREATE TABLE CATEGORIAS (
    id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria TEXT NOT NULL UNIQUE,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE
);
CREATE INDEX idx_nombre_categoria ON CATEGORIAS (nombre_categoria);

-- Tabla: PRODUCTOS
CREATE TABLE PRODUCTOS (
    id_producto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto TEXT NOT NULL,
    descripcion TEXT,
    precio DECIMAL(10,2) NOT NULL,
    tamano producto_tamano DEFAULT 'unico',
    imagen_url TEXT,
    id_categoria INT NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES CATEGORIAS(id_categoria) ON DELETE RESTRICT
);
CREATE INDEX idx_nombre_producto ON PRODUCTOS (nombre_producto);
CREATE INDEX idx_categoria_producto ON PRODUCTOS (id_categoria);
CREATE INDEX idx_activo_producto ON PRODUCTOS (activo);

-- Tabla: CLIENTES
CREATE TABLE CLIENTES (
    id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente VARCHAR(150) NOT NULL,
    telefono VARCHAR(20),
    direccion TEXT,
    notas TEXT,
    activo BOOLEAN DEFAULT TRUE,
    fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_nombre_cliente ON CLIENTES (nombre_cliente);
CREATE INDEX idx_telefono_cliente ON CLIENTES (telefono);

-- Tabla: CANALES_VENTA
CREATE TABLE CANALES_VENTA (
    id_canal INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_canal VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(200),
    activo BOOLEAN DEFAULT TRUE
);

-- Tabla: PEDIDOS
CREATE TABLE PEDIDOS (
    id_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_pedido DATE NOT NULL,
    fecha_limite DATE,
    id_cliente INT NOT NULL,
    id_canal INT NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL DEFAULT 0,
    costo_envio DECIMAL(10,2) DEFAULT 0,
    total DECIMAL(10,2) GENERATED ALWAYS AS (subtotal + COALESCE(costo_envio, 0)) STORED,
    estado pedido_estado DEFAULT 'pendiente',
    metodo_pago VARCHAR(50) DEFAULT 'No especificado',
    requiere_envio BOOLEAN DEFAULT FALSE,
    direccion_envio TEXT,
    notas TEXT,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente) ON DELETE RESTRICT,
    CONSTRAINT fk_pedido_canal FOREIGN KEY (id_canal) REFERENCES CANALES_VENTA(id_canal) ON DELETE RESTRICT
);
CREATE INDEX idx_fecha_pedido ON PEDIDOS (fecha_pedido);
CREATE INDEX idx_estado_pedido ON PEDIDOS (estado);
CREATE INDEX idx_cliente_pedido ON PEDIDOS (id_cliente);
CREATE INDEX idx_canal_pedido ON PEDIDOS (id_canal);
CREATE INDEX idx_pedido_fecha_estado ON PEDIDOS(fecha_pedido, estado);


-- Trigger para actualizar fecha_actualizacion
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.fecha_actualizacion = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_pedidos_updated_at
    BEFORE UPDATE ON PEDIDOS
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Tabla: DETALLE_PEDIDOS
CREATE TABLE DETALLE_PEDIDOS (
    id_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL,
    id_producto INT NOT NULL,
    cantidad INT NOT NULL DEFAULT 1,
    precio_unitario DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,
    CONSTRAINT fk_detalle_pedido FOREIGN KEY (id_pedido) REFERENCES PEDIDOS(id_pedido) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_producto FOREIGN KEY (id_producto) REFERENCES PRODUCTOS(id_producto) ON DELETE RESTRICT,
    CHECK (cantidad > 0)
);
CREATE INDEX idx_pedido_detalle ON DETALLE_PEDIDOS (id_pedido);
CREATE INDEX idx_producto_detalle ON DETALLE_PEDIDOS (id_producto);
CREATE INDEX idx_detalle_producto_pedido ON DETALLE_PEDIDOS(id_producto, id_pedido);

-- Tabla: GASTOS
CREATE TABLE GASTOS (
    id_gasto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(200) NOT NULL,
    categoria_gasto VARCHAR(100) NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    fecha_gasto DATE NOT NULL,
    plataforma VARCHAR(50),
    notas TEXT,
    fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CHECK (monto >= 0)
);
CREATE INDEX idx_fecha_gasto ON GASTOS (fecha_gasto);
CREATE INDEX idx_categoria_gasto ON GASTOS (categoria_gasto);
CREATE INDEX idx_gasto_fecha_categoria ON GASTOS(fecha_gasto, categoria_gasto);

-- ============================================
-- DATOS INICIALES
-- ============================================

INSERT INTO CATEGORIAS (nombre_categoria, descripcion) VALUES
('Collares', 'Collares y gargantillas'),
('Aretes', 'Aretes y pendientes'),
('Manillas/Pulseras', 'Pulseras y manillas'),
('Llaveros', 'Llaveros decorativos y personalizados');

INSERT INTO CANALES_VENTA (nombre_canal, descripcion) VALUES
('Tienda Física', 'Ventas realizadas en el local físico'),
('Instagram', 'Ventas a través de Instagram'),
('WhatsApp', 'Ventas a través de WhatsApp');

INSERT INTO CLIENTES (nombre_cliente, telefono, notas) VALUES
('Cliente General', NULL, 'Cliente sin registro específico');

-- ============================================
-- VISTAS ÚTILES PARA REPORTES
-- ============================================

-- Vista: Ventas de los últimos 7 días
CREATE OR REPLACE VIEW vw_ventas_7_dias AS
SELECT 
    p.id_pedido,
    p.fecha_pedido,
    c.nombre_cliente,
    cv.nombre_canal,
    p.total,
    p.estado
FROM PEDIDOS p
INNER JOIN CLIENTES c ON p.id_cliente = c.id_cliente
INNER JOIN CANALES_VENTA cv ON p.id_canal = cv.id_canal
WHERE p.fecha_pedido >= (CURRENT_DATE - INTERVAL '7 days')
  AND p.estado != 'cancelado'
ORDER BY p.fecha_pedido DESC;

-- Vista: Ventas de los últimos 15 días
CREATE OR REPLACE VIEW vw_ventas_15_dias AS
SELECT 
    p.id_pedido,
    p.fecha_pedido,
    c.nombre_cliente,
    cv.nombre_canal,
    p.total,
    p.estado
FROM PEDIDOS p
INNER JOIN CLIENTES c ON p.id_cliente = c.id_cliente
INNER JOIN CANALES_VENTA cv ON p.id_canal = cv.id_canal
WHERE p.fecha_pedido >= (CURRENT_DATE - INTERVAL '15 days')
  AND p.estado != 'cancelado'
ORDER BY p.fecha_pedido DESC;

-- Vista: Ventas del último mes (30 días)
CREATE OR REPLACE VIEW vw_ventas_30_dias AS
SELECT 
    p.id_pedido,
    p.fecha_pedido,
    c.nombre_cliente,
    cv.nombre_canal,
    p.total,
    p.estado
FROM PEDIDOS p
INNER JOIN CLIENTES c ON p.id_cliente = c.id_cliente
INNER JOIN CANALES_VENTA cv ON p.id_canal = cv.id_canal
WHERE p.fecha_pedido >= (CURRENT_DATE - INTERVAL '30 days')
  AND p.estado != 'cancelado'
ORDER BY p.fecha_pedido DESC;

-- Vista: Productos más vendidos
CREATE OR REPLACE VIEW vw_productos_mas_vendidos AS
SELECT 
    pr.id_producto,
    pr.nombre_producto,
    cat.nombre_categoria,
    SUM(dp.cantidad) as total_vendido,
    SUM(dp.subtotal) as ingresos_totales
FROM PRODUCTOS pr
INNER JOIN DETALLE_PEDIDOS dp ON pr.id_producto = dp.id_producto
INNER JOIN PEDIDOS p ON dp.id_pedido = p.id_pedido
INNER JOIN CATEGORIAS cat ON pr.id_categoria = cat.id_categoria
WHERE p.estado != 'cancelado'
GROUP BY pr.id_producto, pr.nombre_producto, cat.nombre_categoria
ORDER BY total_vendido DESC;

-- Vista: Resumen de ganancias
CREATE OR REPLACE VIEW vw_resumen_ganancias AS
WITH ventas_mes AS (
    SELECT 
        TO_CHAR(fecha_pedido, 'YYYY-MM') as mes,
        COUNT(DISTINCT id_pedido) as total_pedidos,
        SUM(total) as ingresos_totales
    FROM PEDIDOS
    WHERE estado != 'cancelado'
    GROUP BY TO_CHAR(fecha_pedido, 'YYYY-MM')
),
gastos_mes AS (
    SELECT 
        TO_CHAR(fecha_gasto, 'YYYY-MM') as mes,
        SUM(monto) as gastos_totales
    FROM GASTOS
    GROUP BY TO_CHAR(fecha_gasto, 'YYYY-MM')
)
SELECT 
    v.mes,
    v.total_pedidos,
    v.ingresos_totales,
    COALESCE(g.gastos_totales, 0) as gastos_totales,
    v.ingresos_totales - COALESCE(g.gastos_totales, 0) as ganancia_neta
FROM ventas_mes v
LEFT JOIN gastos_mes g ON v.mes = g.mes
ORDER BY v.mes DESC;

-- ============================================
-- FUNCIONES (Equivalente a Procedimientos Almacenados)
-- ============================================

-- Funcion: Crear pedido completo
CREATE OR REPLACE FUNCTION sp_crear_pedido(
    p_fecha_pedido DATE,
    p_id_cliente INT,
    p_id_canal INT,
    p_costo_envio DECIMAL(10,2),
    p_requiere_envio BOOLEAN,
    p_direccion_envio TEXT,
    p_notas TEXT
) RETURNS INT AS $$
DECLARE
    v_id_pedido INT;
BEGIN
    INSERT INTO PEDIDOS (
        fecha_pedido, 
        id_cliente, 
        id_canal, 
        costo_envio, 
        requiere_envio, 
        direccion_envio, 
        notas
    ) VALUES (
        p_fecha_pedido,
        p_id_cliente,
        p_id_canal,
        p_costo_envio,
        p_requiere_envio,
        p_direccion_envio,
        p_notas
    ) RETURNING id_pedido INTO v_id_pedido;
    
    RETURN v_id_pedido;
END;
$$ LANGUAGE plpgsql;

-- Funcion: Agregar producto al pedido
CREATE OR REPLACE FUNCTION sp_agregar_producto_pedido(
    p_id_pedido INT,
    p_id_producto INT,
    p_cantidad INT
) RETURNS VOID AS $$
DECLARE
    v_precio DECIMAL(10,2);
BEGIN
    -- Obtener precio actual del producto
    SELECT precio INTO v_precio 
    FROM PRODUCTOS 
    WHERE id_producto = p_id_producto;
    
    -- Insertar detalle
    INSERT INTO DETALLE_PEDIDOS (id_pedido, id_producto, cantidad, precio_unitario)
    VALUES (p_id_pedido, p_id_producto, p_cantidad, v_precio);
    
    -- Actualizar subtotal del pedido
    UPDATE PEDIDOS 
    SET subtotal = (
        SELECT SUM(subtotal) 
        FROM DETALLE_PEDIDOS 
        WHERE id_pedido = p_id_pedido
    )
    WHERE id_pedido = p_id_pedido;
END;
$$ LANGUAGE plpgsql;

-- Funcion: Obtener ventas por rango de días
CREATE OR REPLACE FUNCTION sp_ventas_ultimos_dias(
    p_dias INT
) RETURNS TABLE (
    id_pedido INT,
    fecha_pedido DATE,
    nombre_cliente VARCHAR,
    nombre_canal VARCHAR,
    total DECIMAL,
    estado pedido_estado,
    productos TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.id_pedido,
        p.fecha_pedido,
        c.nombre_cliente,
        cv.nombre_canal,
        p.total,
        p.estado,
        STRING_AGG(
            CONCAT(pr.nombre_producto, ' (', dp.cantidad, ')'),
            ', '
        ) as productos
    FROM PEDIDOS p
    INNER JOIN CLIENTES c ON p.id_cliente = c.id_cliente
    INNER JOIN CANALES_VENTA cv ON p.id_canal = cv.id_canal
    LEFT JOIN DETALLE_PEDIDOS dp ON p.id_pedido = dp.id_pedido
    LEFT JOIN PRODUCTOS pr ON dp.id_producto = pr.id_producto
    WHERE p.fecha_pedido >= (CURRENT_DATE - (p_dias || ' days')::INTERVAL)
      AND p.estado != 'cancelado'
    GROUP BY p.id_pedido, p.fecha_pedido, c.nombre_cliente, cv.nombre_canal, p.total, p.estado
    ORDER BY p.fecha_pedido DESC;
END;
$$ LANGUAGE plpgsql;
